### ISSUE TITLE
Don't understand README

### ISSUE THREAD

**Issue by SMRTT** [terorie/discord-influx#1]
Hello ! 

I don't understand what we have to do in the part :

Export DISCORD_TOKEN to Bot xxx.

Could you be more specific ?

Thank you

Best regards

**Comment by riptl** [comment]
Hey, thanks for checking out my project.

To use this app, you need a Discord bot and its token.
Suppose the token is `NjA0MjA2OXhkCg` (they look simliar to this):
Execute `export DISCORD_TOKEN="Bot NjA0MjA2OXhkCg"`.

More info on how to set up a bot here:
https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

**Comment by riptl** [comment]
Closing this as I haven't heard back from you in a while.
