### ISSUE TITLE
Running multiple instances?

### ISSUE THREAD

**Issue by MSmithDev** [terorie/discord-influx#2]
If i wanted to monitor two discord servers at one how would this be acchived? i see the dashboard lets you choose which guild to show. Can the same bot be added to another server and then passed another instance of influx discord with the other servers guild/id?

Awesome project by the way.

**Comment by riptl** [comment]
Hey, thanks! The Discord guilds passed to the application take the following form: `guild-name/123456`, where you replace `guild-name` with the name you want to show up in InfluxDB and `123456` with the Discord Guild-ID. 

You can run a single instance for multiple guilds:
`discord-influx guild-1/12345 guild-2/67890`.
Be careful with the start (`-s`) parameter though, it would apply to all guilds at once.

Alternatively, just run multiple instances:
 - `discord-influx guild-1/12345`
 - `discord-influx guild-2/67890`

**Comment by MSmithDev** [comment]
Perfect thank you so much.
