### ISSUE TITLE
Streaming too fast causes api to deny requests

### ISSUE THREAD

**Issue by MSmithDev** [terorie/discord-influx#5]
Im having an issue trying to add one of my servers. It started sending a bunch a data then the api started refusing any more requests. How could i slow this down to get all the data without being penalized by discord?

Flushed 128 aggregations
Flushed 128 aggregations
Flushed 128 aggregations
Flushed 128 aggregations
Flushed 128 aggregations
Flushed 128 aggregations
Flushed 128 aggregations
Flushed 128 aggregations
Flushed 128 aggregations
Flushed 27 aggregations
Message stream aborted: HTTP status client error (403 Forbidden) for url (https://discordapp.com/api/v6/channels/##########messages?limit=100&after=0)

**Comment by riptl** [comment]
I'll look into this. I think rate-limits would be 429 status codes. 403 Forbidden usually means that the passed token doesn't have permission to access a resource (private text channel?). What arguments did you spawn the app with?

**Comment by MSmithDev** [comment]
You are absolutely correct, that was my fault. It was a couple channels it didn't have perms in. Sorry.

**Comment by riptl** [comment]
@MSmithDev Absolutely no worries, I consider it a bug that no better error message gets printed, so I'm reopening this.

**Comment by riptl** [comment]
Done in latest version
