### ISSUE TITLE
Add metrics for users and emojis?

### ISSUE THREAD

**Issue by tsheinen** [terorie/discord-influx#8]
I'm interested in adding metrics for user messages and the rate at which server emojis are used for my own server.  This is something I intend to do myself whenever motivation and free time from school align, just thought I'd go ahead and make an issue to see if anyone has thoughts on the subject.

**Comment by riptl** [comment]
@tcheinen That's a great idea and I'd love to help. My Discord ID is `terorie#2664` if you want to chat about it.

**Comment by riptl** [comment]
Added user message and reactions metrics, see README.
